version: "2"

services:
  nginx:
    build: devops/nginx
    container_name: micro_server
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./:/app
  php:
    build: devops/php-fpm
    container_name: micro_php
    volumes:
      - ./:/app
    working_dir: /app
  qa:
    build: devops/qa
    container_name: micro_validator
    volumes:
      - ./:/code
